export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    SET_TOKEN: "SET_TOKEN",
    SET_CATEGORY: "SET_CATEGORY",
    ADD_CART: "ADD_CART",
    ADJUST_QTY: "ADJUST_QTY",
    REMOVE_CART: "REMOVE_CART"
}